---
title: "City Open Data Portals and Library Data"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r}
# Load relevant libraries
library(dplyr)
#library(Hmisc)
#library(summarytools)
library(tidyr)
library(splitstackshape)
library(httr)
library(ggplot2)
```

```{r}
# retrieve token needed to access data in private github repository
token <- read.delim("~/Google Drive File Stream/My Drive/Keys/g_access.txt", stringsAsFactor = FALSE, header = FALSE)
```

```{r}
# Read in portals data stored in private github repository
url=paste0("https://raw.githubusercontent.com/OpenDataLiteracy/JCDL-Extended/master/Data/KAS_JCDL_PrelimClean_2019-12-16.txt")
x=GET(url, add_headers(Authorization = paste("token", token, sep = " ")))
portals <- content(x, type="text/tab-separated-values", encoding = "UTF-8")
as.data.frame(portals)
```

```{r}
# Read in IMLS data stored in private github repository
url=paste0("https://raw.githubusercontent.com/OpenDataLiteracy/JCDL-Extended/master/Data/IMLS_Data_PLS_FY17_AE_pud17i.csv")
x=GET(url, add_headers(Authorization = paste("token", token, sep = " ")))
imls <- content(x, type="text/csv", encoding = "UTF-8")
as.data.frame(imls)
```

```{r}
# Read in OKFN Open Data Scores data stored in private github repository
#url=paste0("https://raw.githubusercontent.com/OpenDataLiteracy/JCDL-Extended/master/Data/2020-01-16_Download_OpenDataCensusScores.csv")
#x=GET(url, add_headers(Authorization = paste("token", token, sep = " ")))
#census_scores <- content(x, type="text/csv", encoding = "UTF-8")
```

```{r}
# Read in IMLS data stored in private github repository
#url=paste0("https://raw.githubusercontent.com/OpenDataLiteracy/JCDL-Extended/master/Data/PLS_FY17_Outlet_pud17i.csv")
#x=GET(url, add_headers(Authorization = paste("token", token, sep = " ")))
#imls_outlet <- content(x, type="text/csv", encoding = "UTF-8")
```

```{r}
# Fix date formats
portals$DateLibDataLastUpdated <- as.Date(portals$DateLibDataLastUpdated, format = "%Y-%m-%d")
portals$DatePortalAccessed <- as.Date(portals$DatePortalAccessed, format = "%Y-%m-%d")
# Variables to datatype character
portals$Portal_URL <- as.character(portals$Portal_URL)
# Replace N/A with na
portals$OpenDataCensusScore2017 <- ifelse(portals$OpenDataCensusScore2017 != "N/A", portals$OpenDataCensusScore2017, NA)
# Variable to numeric
portals$OpenDataCensusScore2017 <- as.numeric(portals$OpenDataCensusScore2017)
```

```{r}
# Split categories into individual categories based on comma dileaneation, then create dummy variables.
portals <- cSplit_e(portals, split.col = "LibraryDataCategories", sep = ";", type = "character", 
         mode = "binary", fixed = TRUE, fill = 0)
```

```{r}
# Calculate (and add column) the percentage of the city portal data that is public library related
portals$ProportionPublicLibData <- portals$CountVettedPublicLibData / portals$TotalDataSetsAvailable
```

```{r}
#write.csv(portals, "~/Documents/Github/JCDL-Extended/Data/CityPortals_CategoryDummies")
```

```{r} 
# Fix different capitalizations
portals <- portals %>%
       mutate(City = tolower(City),
              State = tolower(State))

imls <- imls %>%
       mutate(CITY = tolower(CITY),
              STABR = tolower(STABR))

# Merge datasets on city, state
merged <- merge(portals, imls, by.x = c("City", "State"), by.y = c("CITY", "STABR"), all.x = TRUE)
```

```{r}
#merged <- merge(temp, imls_outlet, by = "LIBNAME", all.x = TRUE)
```

```{r}
# Variables to datatype factor
# jcdl$Locale <- as.factor(jcdl$Locale)
# jcdl$ReportingStatus <- as.factor(jcdl$ReportingStatus)
# jcdl$MailingZip <- as.factor(jcdl$MailingZip)
# jcdl$Year <- as.factor(jcdl$Year)
```

```{r}
# Check unique values
unique(merged$Software)
```

```{r}
# See what values we have for Locale
unique(merged$GEOCODE)
```

```{r}
# See what values we have for Locale
unique(merged$LOCALE_ADD)
```

```{r}
# See what values we have for Locale
unique(merged$LOCALE_MOD)
```

Definitions of LOCALE features see PLS Data File Documentation (https://www.imls.gov/sites/default/files/fy2017_pls_data_file_documentation.pdf) page 23

```{r}
# Create a Description column for both LOCALE_ADD and LOCALE_MOD and fill based on condition
merged <- merged %>% 
    mutate(LOCALE_ADD_DESCR = case_when(
                LOCALE_ADD == 11 ~ "City Large",
                LOCALE_ADD == 12 ~ "City Midsize",
                LOCALE_ADD == 13 ~ "City Small",
                LOCALE_ADD == 21 ~ "Suburban Large",
                LOCALE_ADD == 22 ~ "Suburban Midsize",
                LOCALE_ADD == 23 ~ "Suburban Small",
                LOCALE_ADD == 31 ~ "Town Fringe",
                LOCALE_ADD == 32 ~ "Town Distant",
                LOCALE_ADD == 33 ~ "Town Remote",
                LOCALE_ADD == 41 ~ "Rural Fringe",
                LOCALE_ADD == 42 ~ "Rural Distant",
                LOCALE_ADD == 43 ~ "Rural Remote"),
           LOCALE_MOD_DESCR = case_when(
                LOCALE_MOD == 11 ~ "City Large",
                LOCALE_MOD == 12 ~ "City Midsize",
                LOCALE_MOD == 13 ~ "City Small",
                LOCALE_MOD == 21 ~ "Suburban Large",
                LOCALE_MOD == 22 ~ "Suburban Midsize",
                LOCALE_MOD == 23 ~ "Suburban Small",
                LOCALE_MOD == 31 ~ "Town Fringe",
                LOCALE_MOD == 32 ~ "Town Distant",
                LOCALE_MOD == 33 ~ "Town Remote",
                LOCALE_MOD == 41 ~ "Rural Fringe",
                LOCALE_MOD == 42 ~ "Rural Distant",
                LOCALE_MOD == 43 ~ "Rural Remote")
           )
```

```{r}
# Change datatype of LOCALE DESCRs
merged$LOCALE_ADD_DESCR <- as.factor(merged$LOCALE_ADD_DESCR)
merged$LOCALE_MOD_DESCR <- as.factor(merged$LOCALE_MOD_DESCR)

```

```{r}
merged %>%
  count(City, State, sort = T) %>%
  filter(n > 1)
```


```{r}
# Count how many library systems are included in the individual cities add colum to dataframe
merged <- merged %>%
  add_count(City, State, name = "CountLibSysinCity")
```

```{r}
multi_libs <- merged %>%
  filter(CountLibSysinCity > 1)

write.csv(multi_libs, "~/Documents/Github/JCDL-Extended/Data/Cities_with_multiple_library_systems")
```

```{r}
single_libs <- merged %>%
  filter(CountLibSysinCity == 1)
```


```{r}
# Uncomment this to view a nice table of descriptive stats in the Viewer
#summarytools::view(summarytools::dfSummary(merged))
```

```{r}
# Uncomment for descriptive stats
#Hmisc::describe(merged)
```

```{r}
# Simple linear regression model
single_libs_PropLR <- lm(ProportionPublicLibData ~ OpenDataCensusScore2017, data=single_libs)
summary(single_libs_PropLR)
```

```{r}
# Simple linear regression model
single_libs_VettLR <- lm(CountVettedPublicLibData ~ OpenDataCensusScore2017, data=single_libs)
summary(single_libs_VettLR)
```

```{r}
# Simple linear regression model
single_libs_TotLR <- lm(TotalDataSetsAvailable ~ OpenDataCensusScore2017, data=single_libs)
summary(single_libs_TotLR)
```

```{r}
# Simple linear regression model
single_libs_PropSizeLR <- lm(ProportionPublicLibData ~ LOCALE_ADD_DESCR, data=single_libs)
summary(single_libs_PropSizeLR)
```

```{r}
# Simple linear regression model
single_libs_VettSizeLR <- lm(CountVettedPublicLibData ~ LOCALE_ADD_DESCR, data=single_libs)
summary(single_libs_VettSizeLR)
```

```{r}
# Simple linear regression model
single_libs_TotSizeLR <- lm(TotalDataSetsAvailable ~ LOCALE_ADD_DESCR, data=single_libs)
summary(single_libs_TotSizeLR)
```


```{r}
# Simple linear regression model total datasets avail and total operating revenue
single_libs_TotRevCityLR <- lm(TotalDataSetsAvailable ~ TOTINCM, data=single_libs)
summary(single_libs_TotRevCityLR)
```


```{r}
# Simple linear regression model
single_libs_TotRevLR <- lm(CountVettedPublicLibData ~ TOTINCM, data=single_libs)
summary(single_libs_TotRevLR)
```

```{r}
# Simple linear regression model
single_libs_TotStaffLR <- lm(CountVettedPublicLibData ~ TOTSTAFF, data=single_libs)
summary(single_libs_TotStaffLR)
```

```{r}
# Create temporary matrix to use in Pearson's correlation
x <- single_libs %>% select(TOTINCM, TOTSTAFF)
x$TOTINCM <- as.numeric(x$TOTINCM)

```

```{r}
# Calculate Pearson's correlation
cor(x, use = "complete.obs")
```


```{r}
# Run (simple) LM dependent variable ProportionPublicLibData against all 
# possible numeric columns

# Adapted from https://stackoverflow.com/questions/30583917/regression-loop-in-r-for-data-frames
# Also indexing tibbles is weird - hence the double brackets. See https://twitter.com/kara_woo/status/1218297608289996800

x <- names(single_libs)

for(i in x)
{ 
    if(is.numeric(single_libs[[i]]))  ##if column is numeric run regression
    {
      fit <- lm(ProportionPublicLibData ~ single_libs[[i]], data=single_libs) 
      coeff <- summary(fit)$coefficients[,4][2] #output only the p-values
      writeLines(paste(coeff,i,"\n"))
    }
}
```

```{r}
# Run (simple) LM dependent variable CountVettedPublicLibData against all 
# possible numeric columns

# Adapted from https://stackoverflow.com/questions/30583917/regression-loop-in-r-for-data-frames
# Also indexing tibbles is weird - hence the double brackets. See https://twitter.com/kara_woo/status/1218297608289996800

for(i in x)
{ 
  if(is.numeric(single_libs[[i]]))  ##if column is numeric run regression
    {       
       fit <- lm(CountVettedPublicLibData ~ single_libs[[i]], data=single_libs) 
       coeff <- summary(fit)$coefficients[,4][2] #output only the p-values
       writeLines(paste(coeff,i,"\n"))
    }
}
```

```{r}
dfm <- reshape2::melt(single_libs[,c('LibraryDataCategories_CatalogAndCirculation','LibraryDataCategories_EventsAndOutreach',
                    'LibraryDataCategories_FacilitiesAndGeospatial', 'LibraryDataCategories_Financial',
                    'LibraryDataCategories_HumanResources', 'LibraryDataCategories_Patrons',
                    'LibraryDataCategories_PublicRecords', 'LibraryDataCategories_TechnologyOfferings')])
```

```{r}
# total datasets by category
dfm <- dfm %>% group_by(variable) %>% summarise("total" = sum(value))
```

```{r}
# barchart of datset totals by category
p <- ggplot(dfm, aes(variable, total)) +
  geom_bar(stat="identity", fill="steelblue") +
  scale_x_discrete(labels=c("LibraryDataCategories_CatalogAndCirculation" = "Catalog & Circulation",
                            "LibraryDataCategories_EventsAndOutreach" = "Events & Outreach",
                            "LibraryDataCategories_FacilitiesAndGeospatial" = "Facilities & Geospatial",
                            "LibraryDataCategories_Financial" = "Financial",
                            "LibraryDataCategories_HumanResources" = "Human Resources",
                            "LibraryDataCategories_Patrons" = "Patrons",
                            "LibraryDataCategories_PublicRecords" = "Public Records",
                            "LibraryDataCategories_TechnologyOfferings" = "Technology Offerings")) +
  theme(axis.text.x = element_text(angle = 75, hjust = 1)) +
  geom_text(aes(label=total), vjust=1.6, color="white", size=3.5) +
  xlab("Dataset Category") +
  ylab("Datasets Available")
p
ggsave("~/Documents/Github/JCDL-Extended/Images/categories_barchart.png")
```

```{r}
# same barchart as above but arranged in descending order of dataset count
p <- ggplot(dfm, aes(x = reorder(variable, -total), total)) +
  geom_bar(stat="identity", fill="steelblue") +
  scale_x_discrete(labels=c("LibraryDataCategories_CatalogAndCirculation" = "Catalog & Circulation",
                            "LibraryDataCategories_EventsAndOutreach" = "Events & Outreach",
                            "LibraryDataCategories_FacilitiesAndGeospatial" = "Facilities & Geospatial",
                            "LibraryDataCategories_Financial" = "Financial",
                            "LibraryDataCategories_HumanResources" = "Human Resources",
                            "LibraryDataCategories_Patrons" = "Patrons",
                            "LibraryDataCategories_PublicRecords" = "Public Records",
                            "LibraryDataCategories_TechnologyOfferings" = "Technology Offerings")) +
  theme(axis.text.x = element_text(angle = 75, hjust = 1)) +
  geom_text(aes(label=total), vjust=-0.4, color="black", size=3.5) +
  xlab("Dataset Category") +
  ylab("Datasets Available")
p
ggsave("~/Documents/Github/JCDL-Extended/Images/categories_barchart_sorted.png")
```

```{r}
nrow(single_libs[single_libs$CountVettedPublicLibData > 0,])
length(single_libs$CountVettedPublicLibData[single_libs$CountVettedPublicLibData > 0])
sum(which(single_libs$CountVettedPublicLibData > 0))
```

```{r}
# Create df with just necessary columns and rows where CountVettedPublicLibData is greater than 0
no_ds <- single_libs %>%
  select(City, State, Software, TotalDataSetsAvailable, CountVettedPublicLibData, ProportionPublicLibData) %>%
  filter(CountVettedPublicLibData > 0)
```

```{r}
# barchart of cities with more than 1 library dataset
no_ds2 <- filter(no_ds, CountVettedPublicLibData > 1)
p1 <- ggplot(no_ds2, aes(City, CountVettedPublicLibData)) +
  geom_bar(stat="identity", fill="steelblue") +
  theme(axis.text.x = element_text(angle = 75, hjust = 1)) +
  xlab("City") +
  ylab("Datasets Available") 
p1
ggsave("~/Documents/Github/JCDL-Extended/Images/cities_barchart.png")
```

```{r}
# sorted barchart of cities with more than 1 library dataset
p1 <- ggplot(no_ds2, aes(x = reorder(City, -CountVettedPublicLibData), CountVettedPublicLibData)) +
  geom_bar(stat="identity", fill="steelblue") +
  theme(axis.text.x = element_text(angle = 75, hjust = 1)) +
  geom_text(aes(label=CountVettedPublicLibData), vjust=-0.4, color="black", size=3.5) +
  xlab("City") +
  ylab("Datasets Available") 
p1
ggsave("~/Documents/Github/JCDL-Extended/Images/cities_barchart_sorted_morethanone.png")
```

```{r, fig.width=10, fig.height=4}
df1 <- data.frame(single_libs$TOTINCM/10000000, single_libs$CountVettedPublicLibData, single_libs$City)
df2 <- reshape2::melt(df1, id.vars='single_libs.City')
head(df2)


ggplot(df2, aes(x=single_libs.City, y=value, fill=variable)) +
    geom_bar(stat='identity', position='dodge')+
  theme(axis.text.x = element_text(angle = 75, hjust = 1))
```


```{r}
p1 <- ggplot(single_libs, aes(City, TOTINCM)) +
  geom_bar(stat="identity", fill="steelblue") +
  theme(axis.text.x = element_text(angle = 75, hjust = 1)) +
  xlab("City") +
  ylab("Total Library Revenue") 
p1
ggsave("~/Documents/Github/JCDL-Extended/Images/cities_revenue_barchart.png")
```

```{r}
single_libs %>%
  select(City, CountVettedPublicLibData) %>%
  arrange(desc(CountVettedPublicLibData))
```

```{r}
single_libs %>%
  select(City, OpenDataCensusScore2017) %>%
  arrange(desc(OpenDataCensusScore2017))
```

```{r}
skimr::skim(single_libs)
```

